version: "3.1"

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${TSUKURU_POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${TSUKURU_POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${TSUKURU_POSTGRESQL_DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
